# Generated by Django 3.2.5 on 2022-09-23 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAdress',
            new_name='ShippingAddress',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipingPrice',
            new_name='shippingPrice',
        ),
    ]
