# Generated by Django 3.2.5 on 2022-10-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_adress_shippingaddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='\t-gavin.w700.h700.2x.jpg', null=True, upload_to=''),
        ),
    ]
