# Generated by Django 3.2.5 on 2022-10-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='use',
            new_name='user',
        ),
    ]
