# Generated by Django 3.2.5 on 2022-10-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_use_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='11-gavin.w700.h700.2x.jpg', null=True, upload_to=''),
        ),
    ]
