# Generated by Django 3.2.5 on 2022-10-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='produst',
            new_name='product',
        ),
    ]
